apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
    test: test
    test1: test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: vckbansod12/argocd-aap1:v1.0.0
          ports:
            - containerPort: 5000